server:
  port: 8080
  
spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
      routes:
        - id: movieRoute 
          uri: http://localhost:8082/ 
          predicates: 
            - Path=/movies/**
        - id: catalogRoute 
          uri: http://localhost:8084/ 
          predicates: 
            - Path=/catalog/**
info:
  app:
    name: gateway-service
    description: Gateway service for microservice test, Rosario Zamudio
    version: 1.0.0
